### ISSUE TITLE
move bookmarks structure to be global

### ISSUE THREAD

**Issue by alfski** [mongern/liquidgalaxy#3]

**Comment by mongern** [comment]
My bookmarks array is global, but I'm creating var bookmark1, var bookmark2, etc inside of my goToBookmark function. Is this still okay?  Here is my code. 

function goToBookmark(bookmarkNumber){
		
		var bookmark1 = {
			title: 'USC',
			pano:  'CAoSLEFGMVFpcFBuZG9iRTRuNVdvMUo2cEV0bkN2S1poVXlVUmxPakVJeDZsajlw',
			heading: 0
		}; 
		
		var bookmark2 = {
			title: 'Sydney',
			pano: 'E045SvTR9OoV1Sh14Fpt0A',
			heading: 0
		};
		
		var bookmark3 = {
			title: 'Disneyland',
			pano: 'CAoSLEFGMVFpcE1zYXo0bjJxVHRPNEpSSUpIaUU5ZzY5aGoxZHZKQjVSQmI0dHNj',
			heading: 45
		};
		
		bookmarks = [bookmark1, bookmark2, bookmark3]; 
		
		panorama.setPano(bookmarks[bookmarkNumber].pano); // lands with heading: 0
		panorama.setPov({heading:bookmarks[bookmarkNumber].heading, pitch: 0});
		// panorama.setOptions(panorama:bookmarks[].pano, {heading:bookmarks[].heading} ); -- pulls these two into one

	}
